
SELECT * FROM customer LIMIT 20;

-- Q1. What is the total revenue generated by  male vs female customers?
SELECT gender, SUM(purchase_amount) as revenue
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT  customer_id, purchase_amount
FROM customer 
WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- Q3. which are the top 5 products with the highest average  review rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) 
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. compare the average purchase amounts between standard and express shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? compare average spend and total revenue b/w subscribers and non-subscribers.
SELECT subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
FROM customer
GROUP BY subscription_status 
ORDER BY total_revenue, avg_spend DESC;

-- Q6. which 5 products have the highest percentage of puchases with discount applied?
SELECT item_purchased,
ROUND(SUM(IF(discount_applied='Yes',1,0))/COUNT(*)*100,2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY 2 DESC LIMIT 5;

-- Q7. Segment customers into new,returning, and loyal based on their total number of previous purchases, and show the count of each segment.
WITH  customer_type as (
SELECT customer_id, previous_purchases,
CASE
WHEN previous_purchases = 1 THEN 'New'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal'
END AS customer_segment
FROM customer
)
SELECT customer_segment, COUNT(*) AS "Number of customers"
FROM customer_type
GROUP BY customer_segment;

-- Q8. what are top3 most purchased products within each category?
WITH item_counts as (
SELECT category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) as item_rank
FROM customer
GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3 ;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. what is the revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
